"""

Revision ID: b9bd8b468b59
Revises: 1eb43ef9864e
Create Date: 2020-10-22 13:09:18.823883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bd8b468b59'
down_revision = '1eb43ef9864e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerability', sa.Column('request', sa.Text(), nullable=True))
    op.add_column('vulnerability', sa.Column('response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability', 'response')
    op.drop_column('vulnerability', 'request')
    # ### end Alembic commands ###
